#!/usr/bin/env python3
"""Generate BEThoven's fixtures.json from openfootball/worldcup.json.

Source: https://github.com/openfootball/worldcup.json (public domain, no API key).
We take only the 72 group-stage matches — knockout matchups aren't known until
the groups settle and are added later via the admin TUI.

The source `time` is local with a UTC offset, e.g. "13:00 UTC-6"; we convert to
RFC3339 UTC (what BEThoven's seeder expects).

Usage:
    python3 scripts/build_fixtures.py            # fetch from GitHub
    python3 scripts/build_fixtures.py path.json  # use a local source file
"""

import json
import re
import sys
import urllib.request
from datetime import datetime, timedelta, timezone

SOURCE_URL = "https://raw.githubusercontent.com/openfootball/worldcup.json/master/2026/worldcup.json"
OUT_PATH = "fixtures.json"
TOURNAMENT = "World Cup 2026"

TIME_RE = re.compile(r"^(\d{1,2}):(\d{2})\s+UTC([+-]\d{1,2})$")


def to_utc(date: str, time: str) -> str:
    """Convert '2026-06-11' + '13:00 UTC-6' to RFC3339 UTC, e.g. 2026-06-11T19:00:00Z."""
    m = TIME_RE.match(time.strip())
    if not m:
        raise ValueError(f"unparseable time: {time!r}")
    hh, mm, off = int(m.group(1)), int(m.group(2)), int(m.group(3))
    local = datetime.strptime(date, "%Y-%m-%d").replace(hour=hh, minute=mm)
    # local = UTC + offset  ->  UTC = local - offset
    utc = (local - timedelta(hours=off)).replace(tzinfo=timezone.utc)
    return utc.strftime("%Y-%m-%dT%H:%M:%SZ")


def main() -> None:
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            src = json.load(f)
    else:
        with urllib.request.urlopen(SOURCE_URL, timeout=30) as r:
            src = json.load(r)

    matches = []
    for mt in src["matches"]:
        group = mt.get("group", "")
        if not group.startswith("Group"):
            continue  # skip knockout rounds
        matches.append(
            {
                "team_a": mt["team1"],
                "team_b": mt["team2"],
                "group_label": group,
                "starts_at": to_utc(mt["date"], mt["time"]),
            }
        )

    matches.sort(key=lambda m: (m["starts_at"], m["group_label"]))
    if len(matches) != 72:
        print(f"WARNING: expected 72 group matches, got {len(matches)}", file=sys.stderr)

    out = {
        "_comment": f"Generated by scripts/build_fixtures.py from openfootball/worldcup.json. "
        f"{len(matches)} group-stage matches. Knockouts are added via the admin TUI.",
        "tournament": TOURNAMENT,
        "matches": matches,
    }
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"wrote {OUT_PATH}: {len(matches)} group-stage matches")


if __name__ == "__main__":
    main()
